/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/virus.glb --transform --precision=10 --shadows --keepnames --meta
Author: Lifetime Studio (https://sketchfab.com/kommus06)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/coronavirus-low-poly-with-good-hdri-361c0fb5ada04a3aa0f8a62f4ccf276e
Title: CoronaVirus Low poly with good hdri
*/

import React, { memo, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const positions = [
  { scale: 1, x: 0, y: 0, z: 0.005 },
  { scale: 0.8, x: -1.8511316776, y: -0.9270576239, z: 2.6414790154 },
  { scale: 0.6, x: -3.2902550697, y: 1.9395018816, z: 2.0899631977 },
  { scale: 0.4, x: 2.2, y: 0.3, z: -2.5 },
  { scale: 0.3, x: 2.7, y: 0.7, z: 0.686 },
  { scale: 0.2, x: -0.6, y: -2.2, z: 2.25 },
];

const Virus = (props) => {
  const { nodes, materials } = useGLTF("/models/virus-transformed.glb");
  return (
    <group {...props} dispose={null}>
      {positions.map((p, i) => (
        <group
          name="Icosphere_2"
          position={[p.x, p.y, p.z]}
          scale={p.scale}
          userData={{ name: "Icosphere_2" }}
          key={i}
        >
          <mesh
            name="Object_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["Material.001"]}
            userData={{ name: "Object_4" }}
          />
          <mesh
            name="Object_6"
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.004"]}
            userData={{ name: "Object_6" }}
          />
          <mesh
            name="Object_7"
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials["Material.005"]}
            userData={{ name: "Object_7" }}
          />
        </group>
      ))}
    </group>
  );
};

export default memo(Virus);

useGLTF.preload("/models/virus-transformed.glb");
