/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/iphone_12_pro.glb --transform --precision=10 --shadows --keepnames --meta
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-12-pro-05dfc991665e45c68c8b7062136c0c6e
Title: iPhone 12 Pro
*/

import React, { memo, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Iphone = (props) => {
  const { nodes, materials } = useGLTF("/models/iphone_12_pro-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[-0.000184533, -2.5883517265, 2.4191436768]}
        rotation={[0, -0.0000737027, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name="RootNode"
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "RootNode" }}
        >
          <group
            name="iPhone__12_Pro"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "iPhone  12 Pro" }}
          >
            <group name="iPhone12_Pro" userData={{ name: "iPhone12 Pro" }}>
              <group name="Camera1" userData={{ name: "Camera1" }}>
                <mesh
                  name="Camera1_PacificBlue_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_PacificBlue_0.geometry}
                  material={materials.PacificBlue}
                  userData={{ name: "Camera1_PacificBlue_0" }}
                />
                <mesh
                  name="Camera1_GrayGlossy_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_GrayGlossy_0.geometry}
                  material={materials.GrayGlossy}
                  userData={{ name: "Camera1_GrayGlossy_0" }}
                />
                <mesh
                  name="Camera1_FrontCamera_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_FrontCamera_0.geometry}
                  material={materials.FrontCamera}
                  userData={{ name: "Camera1_FrontCamera_0" }}
                />
                <mesh
                  name="Camera1_Blackmatte_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_Blackmatte_0.geometry}
                  material={materials.Blackmatte}
                  userData={{ name: "Camera1_Blackmatte_0" }}
                />
                <mesh
                  name="Camera1_Cameralens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_Cameralens_0.geometry}
                  material={materials.Cameralens}
                  userData={{ name: "Camera1_Cameralens_0" }}
                />
                <mesh
                  name="Camera1_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera1_Glass_0.geometry}
                  material={materials.Glass}
                  userData={{ name: "Camera1_Glass_0" }}
                />
              </group>
              <group name="Flash" userData={{ name: "Flash" }}>
                <mesh
                  name="Flash_Flash2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Flash_Flash2_0.geometry}
                  material={materials.Flash2}
                  userData={{ name: "Flash_Flash2_0" }}
                />
                <mesh
                  name="Flash_Flash_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Flash_Flash_0.geometry}
                  material={materials.Flash}
                  userData={{ name: "Flash_Flash_0" }}
                />
              </group>
              <group name="Bezel" userData={{ name: "Bezel" }}>
                <group name="FrontCamera" userData={{ name: "FrontCamera" }}>
                  <mesh
                    name="FrontCamera_Cameralens_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontCamera_Cameralens_0.geometry}
                    material={materials.Cameralens}
                    userData={{ name: "FrontCamera_Cameralens_0" }}
                  />
                  <mesh
                    name="FrontCamera_FrontCamera_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontCamera_FrontCamera_0.geometry}
                    material={materials.FrontCamera}
                    userData={{ name: "FrontCamera_FrontCamera_0" }}
                  />
                  <mesh
                    name="FrontCamera_Glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontCamera_Glass_0.geometry}
                    material={materials.Glass}
                    userData={{ name: "FrontCamera_Glass_0" }}
                  />
                </group>
                <group name="FrontMic" userData={{ name: "FrontMic" }}>
                  <mesh
                    name="FrontMic_GrayGlossy2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontMic_GrayGlossy2_0.geometry}
                    material={materials.GrayGlossy2}
                    userData={{ name: "FrontMic_GrayGlossy2_0" }}
                  />
                  <mesh
                    name="FrontMic_MicrophoneSpeaker_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry}
                    material={materials.MicrophoneSpeaker}
                    userData={{ name: "FrontMic_Microphone/Speaker_0" }}
                  />
                </group>
                <mesh
                  name="Bezel_bezel_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Bezel_bezel_0.geometry}
                  material={materials.bezel}
                  userData={{ name: "Bezel_bezel_0" }}
                />
                <mesh
                  name="FrontCamera001_bezel001_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.FrontCamera001_bezel001_0.geometry}
                  material={materials["bezel.001"]}
                  position={[0, 0, -0.0007138441]}
                  userData={{ name: "FrontCamera.001_bezel.001_0" }}
                />
              </group>
              <group name="Camera3" userData={{ name: "Camera3" }}>
                <mesh
                  name="Camera3_PacificBlue_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_PacificBlue_0.geometry}
                  material={materials.PacificBlue}
                  userData={{ name: "Camera3_PacificBlue_0" }}
                />
                <mesh
                  name="Camera3_GrayGlossy_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_GrayGlossy_0.geometry}
                  material={materials.GrayGlossy}
                  userData={{ name: "Camera3_GrayGlossy_0" }}
                />
                <mesh
                  name="Camera3_FrontCamera_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_FrontCamera_0.geometry}
                  material={materials.FrontCamera}
                  userData={{ name: "Camera3_FrontCamera_0" }}
                />
                <mesh
                  name="Camera3_Blackmatte_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Blackmatte_0.geometry}
                  material={materials.Blackmatte}
                  userData={{ name: "Camera3_Blackmatte_0" }}
                />
                <mesh
                  name="Camera3_Cameralens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Cameralens_0.geometry}
                  material={materials.Cameralens}
                  userData={{ name: "Camera3_Cameralens_0" }}
                />
                <mesh
                  name="Camera3_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera3_Glass_0.geometry}
                  material={materials.Glass}
                  userData={{ name: "Camera3_Glass_0" }}
                />
              </group>
              <group name="Camera2" userData={{ name: "Camera2" }}>
                <mesh
                  name="Camera2_PacificBlue_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_PacificBlue_0.geometry}
                  material={materials.PacificBlue}
                  userData={{ name: "Camera2_PacificBlue_0" }}
                />
                <mesh
                  name="Camera2_GrayGlossy_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_GrayGlossy_0.geometry}
                  material={materials.GrayGlossy}
                  userData={{ name: "Camera2_GrayGlossy_0" }}
                />
                <mesh
                  name="Camera2_FrontCamera_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_FrontCamera_0.geometry}
                  material={materials.FrontCamera}
                  userData={{ name: "Camera2_FrontCamera_0" }}
                />
                <mesh
                  name="Camera2_Blackmatte_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Blackmatte_0.geometry}
                  material={materials.Blackmatte}
                  userData={{ name: "Camera2_Blackmatte_0" }}
                />
                <mesh
                  name="Camera2_Cameralens_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Cameralens_0.geometry}
                  material={materials.Cameralens}
                  userData={{ name: "Camera2_Cameralens_0" }}
                />
                <mesh
                  name="Camera2_Glass_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Camera2_Glass_0.geometry}
                  material={materials.Glass}
                  userData={{ name: "Camera2_Glass_0" }}
                />
              </group>
              <mesh
                name="iPhone12_Pro_Body_0"
                castShadow
                receiveShadow
                geometry={nodes.iPhone12_Pro_Body_0.geometry}
                material={materials.Body}
                userData={{ name: "iPhone12 Pro_Body_0" }}
              />
              <mesh
                name="LiDar_LiDar__0"
                castShadow
                receiveShadow
                geometry={nodes.LiDar_LiDar__0.geometry}
                material={materials.Blackmatte}
                userData={{ name: "LiDar_LiDar _0" }}
              />
              <mesh
                name="Screen_Wallpaper_0"
                castShadow
                receiveShadow
                geometry={nodes.Screen_Wallpaper_0.geometry}
                material={materials.Wallpaper}
                userData={{ name: "Screen_Wallpaper_0" }}
              />
              <mesh
                name="Apple_Logo_Logo_0"
                castShadow
                receiveShadow
                geometry={nodes.Apple_Logo_Logo_0.geometry}
                material={materials.Logo}
                userData={{ name: "Apple Logo_Logo_0" }}
              />
              <mesh
                name="CameraModule001_Glass_0"
                castShadow
                receiveShadow
                geometry={nodes.CameraModule001_Glass_0.geometry}
                material={materials.Glass}
                userData={{ name: "CameraModule.001_Glass_0" }}
              />
              <mesh
                name="CameraModule002_MicrophoneSpeaker_0"
                castShadow
                receiveShadow
                geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry}
                material={materials.MicrophoneSpeaker}
                userData={{ name: "CameraModule.002_Microphone/Speaker_0" }}
              />
            </group>
            <group name="Port" userData={{ name: "Port" }}>
              <mesh
                name="Port_Blackmatte_0"
                castShadow
                receiveShadow
                geometry={nodes.Port_Blackmatte_0.geometry}
                material={materials.Blackmatte}
                userData={{ name: "Port_Blackmatte_0" }}
              />
              <mesh
                name="Port_BodyFrame_0"
                castShadow
                receiveShadow
                geometry={nodes.Port_BodyFrame_0.geometry}
                material={materials.BodyFrame}
                userData={{ name: "Port_BodyFrame_0" }}
              />
            </group>
            <group name="SimTray" userData={{ name: "SimTray" }}>
              <mesh
                name="SimTray_Blackmatte_0"
                castShadow
                receiveShadow
                geometry={nodes.SimTray_Blackmatte_0.geometry}
                material={materials.Blackmatte}
                userData={{ name: "SimTray_Blackmatte_0" }}
              />
              <mesh
                name="SimTray_BodyFrame_0"
                castShadow
                receiveShadow
                geometry={nodes.SimTray_BodyFrame_0.geometry}
                material={materials.BodyFrame}
                userData={{ name: "SimTray_BodyFrame_0" }}
              />
            </group>
            <mesh
              name="iPhone__12_Pro_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              userData={{ name: "iPhone  12 Pro_BodyFrame_0" }}
            />
            <mesh
              name="iPhone__12_Pro_MicrophoneSpeaker_0"
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry}
              material={materials.MicrophoneSpeaker}
              userData={{ name: "iPhone  12 Pro_Microphone/Speaker_0" }}
            />
            <mesh
              name="iPhone__12_Pro_GrayGlossy2_0"
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry}
              material={materials.GrayGlossy2}
              userData={{ name: "iPhone  12 Pro_GrayGlossy2_0" }}
            />
            <mesh
              name="iPhone__12_Pro_Antenna_0"
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_Antenna_0.geometry}
              material={materials.Antenna}
              userData={{ name: "iPhone  12 Pro_Antenna_0" }}
            />
            <mesh
              name="VolumeButton_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.VolumeButton_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              userData={{ name: "VolumeButton_BodyFrame_0" }}
            />
            <mesh
              name="PowerButton_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.PowerButton_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              userData={{ name: "PowerButton_BodyFrame_0" }}
            />
            <mesh
              name="MuteButton_BodyFrame_0"
              castShadow
              receiveShadow
              geometry={nodes.MuteButton_BodyFrame_0.geometry}
              material={materials.BodyFrame}
              userData={{ name: "MuteButton_BodyFrame_0" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default memo(Iphone);

useGLTF.preload("/models/iphone_12_pro-transformed.glb");
