/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/countries.glb --transform --precision=10 --shadows --keepnames --meta
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import AirPlane from "../Plane/AirPlane";

const Countries = (props) => {
  const { nodes } = useGLTF("/models/countries-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <AirPlane rotation={[0.5, 1.2, 0]} scale={1.25} position={[0, 1, 1]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          name="NY"
          receiveShadow
          geometry={nodes.NY.geometry}
          material={nodes.NY.material}
          position={[6.8381786346, 0, -1.2670110464]}
          userData={{ name: "NY" }}
        />
        <mesh
          name="n_korea"
          receiveShadow
          geometry={nodes.n_korea.geometry}
          material={nodes.n_korea.material}
          position={[-3.3133821487, 0, -0.9241276383]}
          userData={{ name: "n_korea" }}
        />
        <mesh
          name="s_korea"
          receiveShadow
          geometry={nodes.s_korea.geometry}
          material={nodes.s_korea.material}
          position={[-2.9149684906, 0, 0.9012759328]}
          userData={{ name: "s_korea" }}
        />
      </group>
    </group>
  );
};

export default Countries;

useGLTF.preload("/models/countries-transformed.glb");
