import { useThree } from "@react-three/fiber";
import { useEffect } from "react";

const pagesLogic = () => {
  const { width: w, height: h } = useThree((state) => state.viewport);

  const PagesData = [
    {
      h1: "The Journey of",
      h2: "Brian Kim",
      tX: 0,
      tY: w <= 5 ? -17 : -10,
      key: 0,
      width: 100,
      size: w <= 5 ? 1.65 : 3,
      p: "",
    },
    {
      h1: "It all started with",
      h2: "Crayons",
      tX: w <= 5 ? 0 : 2.5,
      tY: w <= 5 ? -25 : -10,
      key: 1,
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
      p: "Aren't they just fun to play with? It's limitless what crayons can do. As a little kid, Brian constantly doodled anything he saw or imagined. First step to visualize the imagination.",
    },
    {
      h1: "Pieces of paper? Clean wall?",
      h2: "Just an empty canvas",
      tX: w <= 5 ? 0 : 32,
      tY: w <= 5 ? -50 : -7,
      key: 2,
      size: w <= 5 ? 1 : 2.1,
      width: w <= 5 ? 100 : 35,
      p: "A lot of kids start 'graffiti' pieces. Any clean spaces were just an empty canvas. Brian had to let out his inspiration on where ever he can draw possible. Don't we all have 'trouble' moments?",
    },
    {
      h1: "Mold and sculpt with clay",
      h2: "Let's get hands dirty",
      tX: w <= 5 ? 0 : 4,
      tY: w <= 5 ? -50 : 5,
      key: 3,
      p: "Building and making has always been Brian's favorite hobby. At a young age, Brian transitions his creative medium from 2D to 3D. It's amazing how we can see creativity in space and depth.",
      size: w <= 5 ? 1 : 2,
      width: w <= 5 ? 90 : 40,
    },
    {
      h1: "Create with Lego",
      h2: "Transform into anything",
      tX: w <= 5 ? 0 : 25,
      tY: w <= 5 ? -50 : -5,
      key: 4,
      p: "Most boys have toys and legos in their room. Legos not only teaches us to build cool things, but also teaches us to learn progression. Transformation requires step by step progression, and Brian enjoyed playing with the concept.",
      size: w <= 5 ? 1 : 2.5,
      width: w <= 5 ? 100 : 42.5,
    },
    {
      h1: "Electonic toy",
      h2: "computer games",
      tX: w <= 5 ? 0 : 2,
      tY: w <= 5 ? -50 : -10,
      key: 5,
      p: "Computer games had everything Brian could think of. Pixelated games, 3D modeled games, puzzles. Brian awed the level of designs and ideas were put into program and can be played however he wanted. Games are definitely one of the greatest inspirations to be creative.",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "But of course",
      h2: "Parents scold you for playing too much",
      tX: w <= 5 ? 0 : 22.5,
      tY: w <= 5 ? -50 : -5,
      key: 6,
      p: "",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "What's next?",
      h2: "Let's fly to New York",
      tX: w <= 5 ? 0 : 2,
      tY: w <= 5 ? -50 : -10,
      key: 7,
      p: "Brian decides to study art in New York! There are many creatives in Korea for sure, but no where like New York. It's known to be a melting pot of people from all over the world. A great place for Brian to experience the difference and learn.",
      size: w <= 5 ? 1 : 2,
      width: w <= 5 ? 100 : 32,
    },
    {
      h1: "Witnessing endless possibilities of",
      h2: " 3D Art",
      tX: w <= 5 ? 0 : 35,
      tY: w <= 5 ? -50 : -10,
      key: 8,
      p: "Drawing, Painting, Building, Sculpting, Animating. Everything Brian did during his childhood can be learned in computer. SVA has a great reputation with Computer Art department. Brian enjoyed modeling, sculpting, and look development the most.",
      size: w <= 5 ? 1 : 2,
      width: w <= 5 ? 100 : 30,
    },
    {
      h1: "Showcase creativity",
      h2: "in a TECH world",
      tX: w <= 5 ? 0 : 2,
      tY: w <= 5 ? -48 : -10,
      key: 9,
      p: "It's a previledge to showcase our skills on a big stage. Big tech companies like Google, Amazon, Apple, Wayfair were starting to build 3D projects. Brian witnessed bigger potentials of 3D. He learned to make pretty pictures in school, but in tech world they find a way to interact with it. Are we entering a new era?",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 50,
    },
    {
      h1: "However...",
      h2: "At some point",
      tX: 0,
      tY: w <= 5 ? -35 : -10,
      key: 10,
      p: "",
      size: w <= 5 ? 1.5 : 3,
      width: 100,
    },
    {
      h1: "We experience spontaneous",
      h2: "changes in life",
      tX: w <= 5 ? 0 : 20,
      tY: w <= 5 ? -50 : -10,
      key: 11,
      p: "Every humanity had to experience the unexpected Covid-19. People are getting laid off, companies shutting down, and worst of all, seeing people die. Brian had to go back to Korea to be safe from the madness. It was also a moment when he wanted to do something else other than 3D. ",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "What else ",
      h2: "is out there?",
      tX: 0,
      tY: w <= 5 ? -40 : -10,
      key: 12,
      p: "",
      size: w <= 5 ? 1.5 : 3,
      width: 100,
    },
    {
      h1: "Hello",
      h2: "World",
      tX: w <= 5 ? 0 : 2,
      tY: w <= 5 ? -60 : -10,
      key: 13,
      p: "Hate is a strong word, but Brian hated programming. There were too complicated to look at, and also not so creative. Somebody told him that programming is so much more than writing words, but it's creative thinking. With that in mind, Brian studied front end. Later on he finds out 3D interactive front end.",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "3D +",
      h2: "Engineer",
      tX: w <= 5 ? 0 : 22,
      tY: w <= 5 ? -60 : -10,
      key: 14,
      p: "What a cool idea to make a website where people can interact within 3D space, while using skills we learned from school? This idea sparked Brian to keep moving forward. His young habbits and prior skills weren't put to waste. He decides to catch 2 birds with 1 stone. WebXR isn't known to many of us yet, but it's definitely fast growing trend. ",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "To the path of",
      h2: " new possibilities",
      tX: w <= 5 ? 0 : 2,
      tY: w <= 5 ? -50 : -10,
      key: 15,
      p: "Walt Disney quote, 'We keep moving foward opening up new doors and doing new things... and curiosity keeps leading us down new paths.' We constantly look for new possibilities because of curiosity. Who knows what's ahead of where we're going? Just keep moving forward!",
      size: w <= 5 ? 1 : 3,
      width: w <= 5 ? 100 : 40,
    },
    {
      h1: "Fin?",
      h2: "What's next?",
      tX: 0,
      tY: -10,
      key: 16,
      p: "",
      size: w <= 5 ? 1.5 : 3,
      width: 100,
    },
  ];

  return { PagesData };
};

export default pagesLogic;
